name: Build and Push Frontend Image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag for the Docker image (e.g., v1.0.0, latest)"
        required: true
        default: "latest"

env:
  REGISTRY: ${{ vars.ACR_LOGIN_SERVER }}
  IMAGE_NAME: ${{ vars.FRONTEND_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.REGISTRY }}

      - name: Set TAG
        run: |
          echo "TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Output image info
        run: |
          echo "Built image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "Release tag: ${{ env.RELEASE_TAG }}"
          echo "Also tagged as: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
